# mocca_gui/plotter.py

import numpy as np
import pyvista as pv
from matplotlib.colors import ListedColormap
from PyQt5.QtWidgets import QApplication

from mocca_gui.colormap import my_colormap
from coffee_dac_pipeline import BUNDLE_COL, NETWORK_COL

def plotline_ijk(plotter, edge, color, offset_multiplier=1.0, line_width=3, opacity=0.8):
    a = edge[0:3]
    b = edge[3:6]
    offset = (np.abs(a - b) * 0.1 * offset_multiplier)
    m = ((a + b) / 2) + offset
    spline_points = np.vstack((a, m, b))
    spline = pv.Spline(spline_points, 32)
    plotter.add_mesh(
        spline,
        color=color[:3],
        line_width=line_width,
        render_lines_as_tubes=True,
        opacity=opacity
    )

def add_endpoints(plotter, edge, color, size_scale=1.0, opacity=0.2):
    a = edge[0:3]
    b = edge[3:6]
    pts = np.array([a, b], dtype=np.float64)
    _render_endpoint_cubes(plotter, pts, color, size_scale, opacity)


def _make_unit_cube(half_extent):
    """Return a pv.PolyData cube centred at the origin with the given half-extent.

    Built manually so the result is always a clean, closed surface with correct
    winding – suitable as a glyph geometry for instanced rendering.
    """
    d = float(half_extent)
    verts = np.array([
        [-d, -d, -d], [ d, -d, -d], [ d,  d, -d], [-d,  d, -d],
        [-d, -d,  d], [ d, -d,  d], [ d,  d,  d], [-d,  d,  d],
    ], dtype=np.float32)
    # 6 faces × 2 triangles each
    faces = np.array([
        3, 0, 1, 2,  3, 0, 2, 3,  # -Z
        3, 4, 6, 5,  3, 4, 7, 6,  # +Z
        3, 0, 4, 5,  3, 0, 5, 1,  # -Y
        3, 2, 6, 7,  3, 2, 7, 3,  # +Y
        3, 0, 3, 7,  3, 0, 7, 4,  # -X
        3, 1, 5, 6,  3, 1, 6, 2,  # +X
    ], dtype=np.int32)
    return pv.PolyData(verts, faces)


def _render_endpoint_cubes(plotter, pts, color, size_scale, opacity):
    """Place one axis-aligned cube per row of *pts* in a single batched draw."""
    unique_pts = np.unique(pts, axis=0).astype(np.float64)
    if len(unique_pts) == 0:
        return
    # half-extent: 0.5 * size_scale  →  each cube is size_scale voxels wide
    cube = _make_unit_cube(0.5 * size_scale)
    cloud = pv.PolyData(unique_pts)
    glyphs = cloud.glyph(geom=cube, scale=False, orient=False)
    plotter.add_mesh(glyphs, color=color[:3], opacity=opacity)


def add_endpoints_batch(plotter, edges, color, size_scale=1.0, opacity=0.2):
    '''
    Draw endpoints for an array of edges in a single batched add_mesh call.

    Deduplicates coordinates first so each unique voxel position is drawn
    only once, regardless of how many edges share that endpoint.
    Uses PyVista glyphs (one cube per unique point) for maximum performance.
    '''
    all_pts = np.vstack([edges[:, 0:3], edges[:, 3:6]])
    _render_endpoint_cubes(plotter, all_pts, color, size_scale, opacity)

def generate_centroid_edge(edges_bundle, plotter=None, color=None, size_scale=1.0, opacity=0.2):
    start_points = edges_bundle[:, 0:3]
    end_points = edges_bundle[:, 3:6]

    centroid_start = np.mean(start_points, axis=0)
    centroid_end = np.mean(end_points, axis=0)

    cluster_id = edges_bundle[0, BUNDLE_COL]
    network_id = edges_bundle[0, NETWORK_COL]

    centroid_edge = np.concatenate([
        centroid_start,
        centroid_end,
        np.array([cluster_id, network_id]),
    ])

    if plotter is not None:
        add_endpoints_batch(plotter, edges_bundle, color=color,
                            size_scale=size_scale, opacity=opacity)

    return centroid_edge

class NetworkPlotter:
    def __init__(self, plotter, brain_mesh_path):
        self.plotter = plotter
        self.brain_mesh_path = brain_mesh_path

        # Three-shell priority:
        #   brain3mm_gm.stl    – detailed gyral/sulcal surface (marching-cubes
        #                        from 1mm T1; generated by generate_gm_stl.py)
        #   brain3mm_outer.stl – smooth outer hull fallback
        #   brain3mm_wm.stl    – inner GM/WM boundary
        # Falls back to a single-shell STL when companions are absent.
        import os
        base       = os.path.splitext(brain_mesh_path)[0]
        gm_path    = base + '_gm.stl'
        wm_path    = base + '_wm.stl'
        outer_path = base + '_outer.stl'

        # Choose the best available outer-surface mesh
        if os.path.isfile(gm_path):
            raw_outer = pv.read(gm_path)
        elif os.path.isfile(outer_path):
            raw_outer = pv.read(outer_path)
        else:
            raw_outer = None

        if raw_outer is not None and os.path.isfile(wm_path):
            self.brain_mesh_wm    = pv.read(wm_path)
            self.brain_mesh       = None

            # Pre-compute mean curvature on the outer/GM shell once at load
            # time so every clear() call doesn't re-derive it from scratch.
            # pv.PolyData.curvature() returns a plain ndarray – assign it back.
            raw_outer = raw_outer.compute_normals(cell_normals=False, point_normals=True)
            try:
                curv_arr = raw_outer.curvature(curv_type='mean')  # ndarray, n_points
                lo = float(np.percentile(curv_arr, 10))
                hi = float(np.percentile(curv_arr, 90))
                raw_outer.point_data['Mean_Curvature'] = np.clip(curv_arr, lo, hi).astype(np.float32)
                self._outer_clim = (lo, hi)
                self.brain_mesh_outer = raw_outer
            except Exception:
                self.brain_mesh_outer = raw_outer
                self._outer_clim = (-1.0, 1.0)
        else:
            self.brain_mesh       = pv.read(brain_mesh_path)
            self.brain_mesh_outer = None
            self.brain_mesh_wm    = None
            self._outer_clim      = (-1.0, 1.0)

        self.thicknesses = {}
        self.curvatures = {}
        self.endpoint_sizes = {}

        self.bundle_colors = {}  # Key: (fcn, bundle) → color index
        self.centroid_flags = {}  # (fcn, bundle) → True/False
        self.opacities = {}  # (fcn, bundle) → float

    def clear(self):
        self.plotter.clear()
        if self.brain_mesh_outer is not None:
            lo, hi = self._outer_clim
            # --- Outer GM/CSF shell: curvature-shaded for gyral detail ---
            # Mean curvature pre-computed at load time: sulci (concave) appear
            # darker, gyral crowns (convex) appear lighter via the 'bone' cmap.
            has_curv = 'Mean_Curvature' in self.brain_mesh_outer.point_data.keys()
            if has_curv:
                self.plotter.add_mesh(
                    self.brain_mesh_outer,
                    scalars='Mean_Curvature',
                    cmap='bone',
                    clim=[lo, hi],
                    opacity=0.35,
                    smooth_shading=True,
                    show_scalar_bar=False,
                    specular=0.4,
                    specular_power=20,
                    ambient=0.3,
                    diffuse=0.7,
                )
            else:
                # curvature unavailable – fall back to flat colour
                self.plotter.add_mesh(
                    self.brain_mesh_outer,
                    opacity=0.35, color='wheat',
                    smooth_shading=True,
                    specular=0.3, ambient=0.3, diffuse=0.7,
                )
            # --- Inner WM shell: solid grey boundary, more opaque ---
            self.plotter.add_mesh(
                self.brain_mesh_wm,
                opacity=0.28,
                color='#b0b0b0',
                smooth_shading=True,
                specular=0.2,
                ambient=0.2,
                diffuse=0.8,
            )
        else:
            self.plotter.add_mesh(
                self.brain_mesh, opacity=0.25, color='grey',
                smooth_shading=True
            )

    def draw_selection(
        self,
        edges_net,
        selection,
        endpoint_visible=True,
        stop_flag=None,
        progress_callback=None
    ):
        self.clear()

        total_edges = sum(
            len(edges_net[
                (edges_net[:,NETWORK_COL] == item['fcn']) &
                (edges_net[:,BUNDLE_COL] == b)
            ])
            for item in selection
            for b in (
                np.unique(edges_net[edges_net[:,NETWORK_COL]==item['fcn']][:,BUNDLE_COL])
                if item['bundle'] == "All"
                else [item['bundle']]
            )
        )
        if total_edges == 0:
            total_edges = 1

        edges_drawn = 0

        for item in selection:
            fcn = item['fcn']
            bundle = item['bundle']

            if bundle == "All":
                bundles = np.unique(edges_net[edges_net[:,NETWORK_COL]==fcn][:,BUNDLE_COL])
            else:
                bundles = [bundle]

            for b in bundles:
                # check bundle color first, then FCN-wide color
                idx = self.bundle_colors.get((fcn, int(b)))

                if idx is None:
                    idx = self.bundle_colors.get((fcn, 'All'))

                if idx is not None:
                    color = my_colormap.colors[idx]
                else:
                    color = my_colormap.colors[fcn % len(my_colormap.colors)]
                    #color_list = np.array([
                #"""more contrasted FCN-colors:"""" color = np.array([[153/255, 0.0, 0.0, 1.0], [0.0, 153/255, 0.0, 1.0], [0.0, 0.0, 153/255, 1.0], [255/255, 128/255, 0.0, 1.0],[128/255, 0.0, 255/255, 1.0]])
                
                # Get centroid toggle state – default False to show all edges
                use_centroid = self.centroid_flags.get((fcn, int(b)), False)

                edges = edges_net[
                    (edges_net[:,NETWORK_COL] == fcn) &
                    (edges_net[:,BUNDLE_COL] == b)
                ]

                if use_centroid and len(edges) > 0:
                    endpoint_size = self.endpoint_sizes.get((fcn, int(b)), 1.0)
                    # generate centroid edge; endpoints drawn via batched glyphs
                    centroid_edge = generate_centroid_edge(
                        edges,
                        plotter=self.plotter if endpoint_visible else None,
                        color=color,
                        size_scale=endpoint_size,
                        opacity=self.opacities.get((fcn, int(b)), 0.8),
                    )

                    plotline_ijk(
                        self.plotter,
                        centroid_edge,
                        color=color,
                        offset_multiplier=self.curvatures.get((fcn, int(b)), 1.0),
                        line_width=self.thicknesses.get((fcn, int(b)), 3),
                        opacity=self.opacities.get((fcn, int(b)), 0.8)
                    )

                    edges_drawn += len(edges)
                    if progress_callback:
                        progress_callback(int((edges_drawn / total_edges) * 100))

                    # yield to Qt event loop between bundles so the UI stays responsive
                    QApplication.processEvents()
                    if stop_flag and stop_flag():
                        print("Plotting cancelled.")
                        return

                else: 

                    for edge in edges:
                        if stop_flag and stop_flag():
                            print("Plotting cancelled.")
                            return

                        thickness = self.thicknesses.get((fcn, int(b)), 3)
                        curvature = self.curvatures.get((fcn, int(b)), 1.0)
                        endpoint_size = self.endpoint_sizes.get((fcn, int(b)), 1.0)

                        plotline_ijk(
                            self.plotter,
                            edge,
                            color=color,
                            offset_multiplier=curvature,
                            line_width=thickness,
                            opacity=self.opacities.get((fcn, int(b)), 0.8)
                        )

                        if endpoint_visible:
                            add_endpoints(
                                self.plotter,
                                edge,
                                color=color,
                                size_scale=endpoint_size,
                                opacity=self.opacities.get((fcn, int(b)), 0.8)
                            )

                        edges_drawn += 1

                        # call processEvents() every N edges
                        if edges_drawn % 10 == 0:
                            QApplication.processEvents()

                            if progress_callback:
                                percent = int((edges_drawn / total_edges) * 100)
                                progress_callback(percent)

        self.plotter.reset_camera()
        self.plotter.render()


